//EXERCICIO DE INTERPRETACAO DE CODIGO
//PRIMEIRA QUESTAO
//A
//SERA IMPRESSO 10 E 50.
//B
//SE RETIRASSE OS DOIS CONSOLE.LOG SIMPLESMENTE O RESULTADO
//NAO IRIA APARECER, POIS NADA TEM A SER IMPRESSO


//SEGUNDA QUESTAO
//letra a- ESSA FUNCAO VAI VERIFICAR SE O TEXTO DIGITADO PELO USUARIO
//ESTA EM MAIUSCULO OU CONTEM CENOURA, PARA APRESENTAR RE-
//SULTADO VERDADEIRO OU FALSO.

//letra b-
//i. true
//ii. true
//iii. true

// EXERCICIO DE ESCRITA DE CÓDIGO

//PRIMEIRA QUESTAO
console.log("Eu sou Thayane, tenho 32 anos, moro em Salvador e sou estudante")
